## w5-220502-mon

### callback 함수

```js
function makeAmericano(callback) {
    setTimeout(() => {
        callback("americano")
    }, 60000);
}
```

***

## w5-220503-tue

###  ES6 desructing
```js
// 객체 destructing
const duck = {
    name: "duck",
    sound: "quack",
};

//const name = duck.name;
//const sound = duck.sound;
const {name, sound} = duck

console.log("name", name);
console.log("sound", sound);

//출력:
//name duck
//sound quack

// 배열 destructing
const animals = ["duck", "cat", "bear"];

//const first = animals[0];
//const second = animals[1];
//const third = animals[2];
const [first, second, third] = animals

console.log("first", first);
console.log("second", second);
console.log("third", third);
```

### 비동기 코딩
* callback 지옥 -> promise로 해결
* promise 지옥 -> async-await으로 해결


### callback 활용
```js
function countDown(count, callback) {
    console.log(count);
    
    if (count === 0) {
        callback();
        return;
    }
    
    setTimeout(() => {
        countDown(count - 1, callback);
    }, 1000);
}

// 5초 뒤 callback 함수 실행
countDown(5, ()=>{console.log("BOOM!")})
```

### callback & promise
```js
// adder 함수 정의: resolve 되었을 때의 함수
function adder(a, b, callback) {
    if (a == 0 || b == 0) {
        callback("no zero", null);
        return;
    }
    console.log(`${a}+${b}=${a + b}`);
    callback(null, a + b);
}

// handle_error 함수 정의: error일 때의 함수
function handle_error(error) {
    console.log("ERROR: ", error);
}

// adder를 promise 객체로 만들어주기
function adder_promise(a, b) {
    return new Promise((resolve, reject) => {
        adder(a, b, (err, result) => {
            if (err) {
                /* 1. promise 에서 에러 처리하기 */
                reject(err)
                return;
            }
            /* 2. promise 에서 결과값 처리하기 */
            resolve(result)
        });
    });
}

// promise 함수 실행
function add_all(a, b, c) {
    adder_promise(a, b)
        /* 3. then 을 활용하여 result 와 c 를 add_promise 하기 */
        .then((result) => {
            return adder_promise(result, c)
        })
        .then(result2 => {
            console.log(`${a}+${b}+${c}=${result2}`);
        })
        /* 4. catch 를 활용하여 promise 의 에러를 handle_error 함수로 전달하기 */
        .catch((err) => {
            handle_error(err);
        })
}
```

### promise -> async/await
```js
// promise 생성 
function adder_promise(a, b) {
    return new Promise((resolve, reject) => {
        resolve(a+b);
    });
}

// promise-then으로 실행
function main_promise(a, b, c, d) {
    Promise.all([
        adder_promise(a, b),
        adder_promise(c, d),
    ])
    .then(([r1, r2]) => {
        return adder_promise(r1, r2);
    })
    .then((r3) => {
        console.log(`${a}+${b}+${c}+${d}=${r3}`);
    });
}

// async/await으로 promise 실행
async function main(a, b, c, d) {
    /* 2. 두 promise 함수를 동시에 실행하여 결과를 r1, r2에 저장 */
    const [r1, r2] = await Promise.all([
        adder_promise(a, b),
        adder_promise(c, d),
    ])
    /*3. r1 과 r2 를 한번 더 adder_promise 로 실행 */
    const r3 = await adder_promise(r1, r2)
    console.log(`${a}+${b}+${c}+${d}=${r3}`);
}
main(1,2,3,4);
```

